name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Create schema with...
        2. Set environment variable...
        3. Call createEnv()...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Minimal Reproduction Code
      description: Please provide a minimal code example that reproduces the issue.
      render: typescript
      placeholder: |
        import { createEnv } from '@kawaaaas/lambda-env-schema';

        const env = createEnv({
          // your schema
        });

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of lambda-env-schema are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      placeholder: "20.10.0"
    validations:
      required: true

  - type: input
    id: typescript-version
    attributes:
      label: TypeScript Version
      description: What version of TypeScript are you using?
      placeholder: "5.3.0"

  - type: dropdown
    id: runtime
    attributes:
      label: Runtime Environment
      options:
        - AWS Lambda
        - Local Development
        - Docker
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
